// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © donnieashok

//@version=5
strategy("DAX Long", overlay=true, pyramiding=30, initial_capital=3000, currency=currency.EUR, commission_value=0.02, commission_type=strategy.commission.percent)

// === INPUT BACKTEST RANGE ===
fromDay   = input.int(defval = 1,    title = "From Day",    minval = 1, maxval = 31)
fromMonth = input.int(defval = 12,    title = "From Month",  minval = 1, maxval = 12)
fromYear  = input.int(defval = 2020, title = "From Year",   minval = 1970)
thruDay   = input.int(defval = 1,    title = "Thru Day",    minval = 1, maxval = 31)
thruMonth = input.int(defval = 12,    title = "Thru Month",  minval = 1, maxval = 12)
thruYear  = input.int(defval = 2021, title = "Thru Year",   minval = 1970)

// === FUNCTION EXAMPLE ===
start     = timestamp(fromYear, fromMonth, fromDay, 00, 00)            // backtest start  window
finish    = timestamp(thruYear, thruMonth, thruDay, 23, 59)            // backtest finish window
window()  => time >= start and time <= finish ? true : false           // create function "within window of time"

//avgHL = ta.ema(high - low, 20)

hiWk = ta.highest(close, 170)[1]
loWk = ta.lowest(close, 170)[1]
hiLoWk = (hiWk - loWk)
weekrangebuy = hiWk - (hiLoWk * 0.99)

hiHigh = ta.highest(high, 20)[1]
loLow = ta.lowest(low, 20)[1]
hiLoDif = (hiHigh - loLow)
daysafebuy = (hiHigh - (hiLoDif * 0.99)) * 0.95

longCondition = (daysafebuy > close or weekrangebuy > close) and window()

// 1 qty refers to 100 * 10
if (longCondition)
    strategy.entry("Long", strategy.long, qty=1, comment=str.tostring(close)+" "+str.tostring(strategy.position_size+1))
    strategy.exit("long", "Long", profit = 10000, comment=str.tostring(close)+" "+str.tostring(strategy.position_size))

//if (not window())
//    strategy.close_all()
